[project]
name = "traopy_visualize"
version = "0.1.0"
description = "Add your description here"
dependencies = [
  "graphviz==0.20.3",
  "matplotlib==3.10.1",
  "networkx==3.4.1",
  "pygraphviz==1.14",
]

[build-system]
requires = ["hatch==1.14.1"]
build-backend = "hatchling.build"
