[workspace.dependencies]
axum = "0.7"
axum-extra = { version = "0.9", features = [ "typed-header" ] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tower = "0.5.1"
tower-http = { version = "0.5.0", features = ["add-extension", "trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0", features = ["serde", "v4", "v7"] }
reqwest = "0.12.5"
anyhow = "1.0"
thiserror = "1.0.63"
ssh2 = "0.9.4"
byte-unit = "5.1.6"
futures = "0.3.31"
chrono = "0.4.39"
bytes = "1.1.0"
prost = "0.13.4"
prost-types = "0.13.4"
tonic = "0.12.3"
tonic-types = "0.12.3"
tonic-web = "0.12.3"
tonic-build = "0.12.3"
pyo3 = { version = "0.23.4", features = ["extension-module"] }
pyo3-stub-gen = "0.7.0"


[workspace]
members = [
    "judge_control_app",
    "writerutil",
    "grpc_schema",
    "judge_core",
    "traopy",
]
resolver = "2"
