[project]
name = "traojudge-judge-workspace"
version = "0.1.0"
description = "Rye workspace for traO-Judge-judge repository"
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "ipykernel==6.29.5",
    "dotenv==0.9.9",
    "./pylib/traopy_util",
    "./pylib/traopy_builder",
    "./pylib/traopy_visualize",
]

[tool.rye]
managed = true
virtual = true