[project]
name = "traojudge-judge-workspace"
version = "0.1.0"
description = "Rye workspace for traO-Judge-judge repository"
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
dev-dependencies = []

[tool.rye.workspace]
members = [
    "pylib/traopy_builder",
    "pylib/traopy_util",
    "pylib/traopy_visualize",
    "pylib/example",
]

[tool.setuptools.packages.find]
include = ["pylib"]
