[package]
name = "judge_control_app"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tonic = { workspace = true }
judge_core = { path = "../../lib/judge_core" }
local_problem_registry = { path = "../../lib/local_problem_registry" }
local_jobapi = { path = "../../lib/local_jobapi" }
back_judge_grpc = { path = "../../lib/back_judge_grpc" }
