[project]
name = "traopy_example"
version = "0.1.1"
description = "Example of problem for traOJudge"
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "ipykernel==6.29.5",
    "dotenv==0.9.9",
    "traopy_util",
    "traopy_builder",
]