name: _test-rust

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-all-features-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build dependencies
      run: cargo build --locked --all-features

  build-judge-control-app:
    needs: build-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build test for judge_control_app
      run: cargo build --locked -p judge_control_app
  build-backend-app:
    needs: build-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build test for backend_app
      run: cargo build --locked -p backend_app
  build-exec-app:
    needs: build-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build test for exec_app
      run: cargo build --locked -p exec_app
  cargo-test:
    needs: build-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run test
      run: cargo test --locked
  cargo-format:
    needs: build-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check formatting
      run: export CODEGEN_SKIP=true && cargo fmt --all --check
