name: Build judge-control-app

on:
  push:
    branches:
      - develop
      - fix/#309-fix-s3-download

jobs:
  build-judge-control-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'us-west-2'
          role-to-assume: 'arn:aws:iam::222634386193:role/GitHub_OIDC_traO-infra'
      - name: Build
        run: cargo build -p judge_control_app --bin main --release
      - name: Rename binary
        run: cp target/release/main target/release/judge-control-app
      - name: Upload to S3
        run: aws s3 cp target/release/judge-control-app s3://trao-infra-resources/judge-control-app/
