name: Build exec-app

on:
  push:
    branches:
      - main

jobs:
  build-exec-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-exec-app
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'us-west-2'
          role-to-assume: 'arn:aws:iam::222634386193:role/GitHub_OIDC_traO-infra'
      - name: Build
        run: cd app/exec_app; cargo build --release
      - name: Rename binary
        run: cp target/release/exec_app target/release/exec-app
      - name: Upload to S3
        run: aws s3 cp target/release/exec-app s3://trao-infra-resources/exec-app/
