name: CI (develop)

permissions:
  contents: read

on:
    workflow_call:
    pull_request:
      branches: [ "develop" ]  

jobs:
  cargo-build:
    uses: ./.github/workflows/_rust-build-check.yml
  cargo-fmt:
    uses: ./.github/workflows/_cargo-fmt.yml
  cargo-test:
    uses: ./.github/workflows/_cargo_test.yml
  uv-build:
    uses: ./.github/workflows/_uv-build.yml
  backend-integration-test:
    uses: ./.github/workflows/_backend-integration-test.yml
