name: CI (develop)

permissions:
  contents: write

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]  

jobs:
  cargo-build:
    permissions:
      contents: read
    uses: ./.github/workflows/_rust-build-check.yml
  cargo-fmt:
    permissions:
      contents: write
    uses: ./.github/workflows/_cargo-fmt.yml
